version: '3'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5439:5432
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

volumes:
  db-data:
